### PR TITLE
word fixes

### PR DESCRIPTION
**Pull request by roliverio**
Fixing hyphens in this app as well.

(didn't touch the files_archive app as i've already created an issue there)

### CODE REVIEW

**Comment by rotdrop** [comment]
Thanks, I will now upload another release in order to fix stupid things with the old broken release. Your fixes will be merged into the following release.

**Comment by roliverio** [comment]
Let us know as soon you add another release, i want to avoid revisiting the translation if i complete it now. Thanks!

**Comment by rotdrop** [comment]
I am merging now into main before merging a rather large feature branch. AFAIK, three variants exist for endpoint vs. end point vs. end-point, but as I assume that your native language is English I go gladly with your suggestions.

**Comment by rotdrop** [comment]
Ok, one of the page-label -> "page label" fixes was for the id-attribute of an HTML element. I am undoing that as I do not want to have spaces there.

**Pull request merged**
